### ISSUE TITLE
nri-port-monitor executable bundled in 1.2 release is 0-byte file

### ISSUE THREAD

**Issue by haidangwa** [newrelic/nri-port-monitor#4]
We used https://github.com/newrelic/nri-port-monitor/releases/download/1.2/nri-port-monitor.tar.gz in our deployment of this nri-port-monitor integration, and we also used the chef resource provided by [newrelic/infrastructure-agent-chef](https://github.com/newrelic/infrastructure-agent-chef/blob/master/libraries/integration.rb). 

The chef resource was called `newrelic_infra_integration`, and it created the definition file under /var/db/newrelic-infra/custom-integrations/nri-port-monitor.yaml. This file was rendered as follows:

```
[root@am-uw2-0a9c9667 custom-integrations]# cat nri-port-monitor.yaml 
---
name: com.newrelic.tcp-port-monitor
protocol_version: 1
os: linux
commands:
  metrics:
    command:
      - /opt/newrelic-infra/nri-port-monitor/nri-port-monitor
      - --metrics
    interval: 10
    prefix: integration/nri-port-monitor
```

The problem with this that the tar.gz file that the executable given in this file is a 0-byte file. The file is bundled in the 1.2 release of this repo at https://github.com/newrelic/nri-port-monitor/releases/download/1.2/nri-port-monitor.tar.gz.

In order to workaround this problem, I needed to specify `bin_dir` and `bin` properties when I use the `newrelic_infra_integration` in chef, like so:

```
  action: :create,
  bin: '/opt/newrelic-infra/nri-port-monitor/bin/port-monitor',
  bin_dir: '/opt/newrelic-infra/nri-port-monitor/bin',
  integration_name: 'com.newrelic.tcp-port-monitor',
  remote_url: \
    'https://github.com/newrelic/nri-port-monitor/releases/download/1.2/nri-port-monitor.tar.gz',
  commands: { metrics: %w[--metrics] },
  instances: [
    {
      name: "#{node.name}-nginx-80",
      command: 'metrics',
      arguments: {
        address: '127.0.0.1:80',
        network: 'tcp',
        timeout: 5
      },
      labels: {
        environment: node.chef_environment
      }
    },
```

Perhaps when the tar.gz file was created, the nri-port-monitor executable was a symlink on the build machine that was linked to bin/port-monitor, and without the proper tar options, the symlink was converted to a 0-byte file before being bundled up in the tar file.
